---
# tasks file for wubaLAMP | PHP

- name: PHP 5 | Minimal Packages
  apt: "name={{ item }} state=present"
  with_items:
    - php5
    - php5-mysql
    - php5-sqlite

- name: PHP 5 | Other Packages
  apt: "name={{ item }} state=present"
  with_items:
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-dev
    - php5-imagick
    - php5-imap
    - php5-mcrypt
    - php-apc
    - php-pear

- name: PHP 5 | Get Composer Installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: PHP 5 | Run Composer Install
  command: >
    php composer-installer.php
    chdir=/tmp
    creates=/usr/local/bin/composer

- name: PHP 5 | Make Composer Globally Acessible
  shell: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer