---
# tasks file for wubaCore | systemLocale

- name: System Locale | Language Packs
  apt: "name={{ item }} state=present"
  with_items:
    - language-pack-en
    - language-pack-pt

- name: System Locale | Copy Files
  copy:
    src: locale
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
    force: yes
  notify:
    - system locale | compile files
    - system locale | reconfigure