---
# handlers file for wubaCore

- name: system locale | compile files
  command: locale-gen en_US.UTF-8

- name: system locale | reconfigure
  command: dpkg-reconfigure locales

- name: system timezone | reconfigure
  command: dpkg-reconfigure -f noninteractive tzdata